// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJz4lxQpf4tvqgywD3-S5-r4c4iK60W2o',
    appId: '1:404091520006:web:3e850c8c20e01fc36b6f87',
    messagingSenderId: '404091520006',
    projectId: 'ghosting-f987a',
    authDomain: 'ghosting-f987a.firebaseapp.com',
    storageBucket: 'ghosting-f987a.firebasestorage.app',
    measurementId: 'G-CRW6CQJJZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO-dfK5m344ype6JH7w5iFBorNWZNkRQI',
    appId: '1:404091520006:android:6e7810f51fa129f26b6f87',
    messagingSenderId: '404091520006',
    projectId: 'ghosting-f987a',
    storageBucket: 'ghosting-f987a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWlSqpaG08lMuiitnRDyc-QLNzyDM6llo',
    appId: '1:404091520006:ios:23b1ed61bfc6696f6b6f87',
    messagingSenderId: '404091520006',
    projectId: 'ghosting-f987a',
    storageBucket: 'ghosting-f987a.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWlSqpaG08lMuiitnRDyc-QLNzyDM6llo',
    appId: '1:404091520006:ios:23b1ed61bfc6696f6b6f87',
    messagingSenderId: '404091520006',
    projectId: 'ghosting-f987a',
    storageBucket: 'ghosting-f987a.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJz4lxQpf4tvqgywD3-S5-r4c4iK60W2o',
    appId: '1:404091520006:web:3bd583cfb840ceb66b6f87',
    messagingSenderId: '404091520006',
    projectId: 'ghosting-f987a',
    authDomain: 'ghosting-f987a.firebaseapp.com',
    storageBucket: 'ghosting-f987a.firebasestorage.app',
    measurementId: 'G-LJ4S5HCN19',
  );
}
